
spring.datasource.url=jdbc:mysql://localhost:3306/rentix_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
# Înlocuiește 'parola_ta' cu parola reală setată în MySQL Workbench
spring.datasource.password=Mateietare2008
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Setări Hibernate (Generarea automată a tabelelor)
# 'update' va crea tabelele automat la prima rulare și le va păstra ulterior
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. Configurare Încărcare Fișiere (Imagini)
# Permitem fișiere de până la 5MB
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

#4.  Portul aplicației (opțional, default este 8080)
server.port=8080

# 5. Gestionarea resurselor statice (pentru a vedea index.html direct)
spring.web.resources.static-locations=classpath:/static/

# 6. CLOUDINARY (UPLOAD IMAGINI)
# aici pui datele din dashboard Cloudinary
cloudinary.cloud-name=YOUR_NAME
cloudinary.api-key=YOUR_KEY
cloudinary.api-secret=YOUR_SECRET